### ISSUE TITLE
Import solution error

### ISSUE THREAD

**Issue by keenhon** [ludovicperrichon/PowerApps-and-PowerAutomate-Solution-Replace#1]
Hi there,

I am trying to use your script to Export my powerapp solution (with flows and apps) and import it again.

I am hitting this problem which I don't know what I have not replaced. I tried to find the value 09edef3a-677b-eb11-a812-002248173fca in my solution, but there isn't any.

Here's the error, hope you can assist to guide me in the right direction
---------------------------

failed to import: Cannot insert duplicate key exception when executing non-query: System.Data.SqlClient.SqlCommand Exception: System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'cndx_PrimaryKey_connectionreference'. Cannot insert duplicate key in object 'dbo.connectionreferenceBase'. The duplicate key value is (09edef3a-677b-eb11-a812-002248173fca, 0, Jan 1 1900 12:00AM). The statement has been terminated. at Microsoft.Crm.CrmDbConnection.HandleExecutionException(Exception exception, String commandText, IDbConnection connection, IDbCommand command, IDbTransaction transaction, Boolean isOpen, Int32 commandTimeout, Int32& retryCount) at Microsoft.Crm.CrmDbConnection.InternalExecuteWithRetry[TResult](Func`1 executeMethod, IDbCommand command, ICrmTransaction crmTransaction) at Microsoft.Crm.CrmDbConnection.<>c__DisplayClass161_0.<InternalExecuteNonQuery>b__0() at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties) at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func) at Microsoft.Crm.Platform.Server.DataEngine.SqlDataAccessManager.ExecuteNonQuery(IDbCommand command, ISqlExecutionContext context, Int32 sourceLineNumber, String memberName, String sourceFilePath) at Microsoft.Crm.BusinessEntities.BusinessProcessObject.ExecuteNonQuery(IDbCommand command, ISqlExecutionContext context) at Microsoft.Crm.Platform.SolutionAwareComponents.CreateInstanceActionBase.ExecuteCreate(IDbCommand command, ExecutionContext context) ClientConnectionId:d405f72a-02fb-4f4c-ad3d-f6b6b79e228e Error Number:2627,State:1,Class:14 ClientConnectionId before routing:598f9fb3-3099-4093-ada4-88472f9118fb Routing Destination:ef830c4c1714.tr498.eastasia1-a.worker.database.windows.net,11027

**Comment by ludovicperrichon** [comment]
Hi,

Never had this error so far. It is talking about a duplicate key value
09edef3a-677b-eb11-a812-002248173fca.
Is this value into your json ? If so, what is behind this guid ?

*Ludovic Perrichon*

*E-Mail :* ***@***.***
*Web-site : *www.ludovicperrichon.com

**Comment by keenhon** [comment]
I tried to find the value in all the json and xml. No such value at all. The nearest I found was suffix "eb11-a812-002248173fca" which appears in flow records of "customizations.xml" and "solution.xml"

There is also reference of the flow in one of my powerapp and the same prefix shows up in "Properties.json"

**Comment by ludovicperrichon** [comment]
I am going to try to reproduce the issue, did you export a whole solution
or just a canvas application or a simple flow ?
At the time I have made this solution (more than a year a go), I was not
playing with the solution so far, maybe it is time for the script to have
an update.
If it is a solution, what do you have in your solution? (A powerapps, a
flow...)

*Ludovic Perrichon*

*Web-site : *www.ludovicperrichon.com

**Comment by keenhon** [comment]
I exported the app with all the flows. Downloaded the error log, seems to be stopping at the solution level.

[IRIMS CAS_import_error.xlsx](https://github.com/ludovicperrichon/PowerApps-and-PowerAutomate-Solution-Replace/files/6266157/IRIMS.CAS_import_error.xlsx)

**Comment by ludovicperrichon** [comment]
Are you trying to upload the solution in an environment where the solution
already exists ?

*Ludovic Perrichon*

*Web-site : *www.ludovicperrichon.com

**Comment by keenhon** [comment]
Yes. I want to clone my solution to use diffent sharepoint lists in a different sharepoint site in the same environment.

**Comment by ludovicperrichon** [comment]
In the meantime, as a workaround, maybe export your powerapps and flow
itself. Run the script on the different zip file you have, create the new
solution manually and re-import all the zipped files.


*Ludovic Perrichon*

*Web-site : *www.ludovicperrichon.com

**Comment by keenhon** [comment]
Will try that later. It's 1am here. Thanks for the prompt response.

**Comment by keenhon** [comment]
I moved past this error. Seems need to rename all "connectionreferencelogicalname" with unique ID.

Another weird problem I found. The output zip  seems to have error reading workflows folder when importing. I manually re-created the zip using 7zip and it will pass through. Not sure why the zip also has small differences in size.

Clearing rest of the errors now.

**Comment by keenhon** [comment]
I made some code changes but can't seem to commit, permission issues. The code doesn't process xml files which are needed in solution package. Also there is a file with a weird name that cannot be processed, so I just added a logic to skip it.

Here's part of the code.
                ".xml"{
					if (-Not $content.Name.StartsWith("[")) {
						Write-Host "Replacing value in $thisFolder\$content"
						EditFileTemplate "$thisFolder\$content"
						Write-Host "$thisFolder\$content done" -ForegroundColor Green
					}
                }
